databases:
  - name: hireme
    plan: free
    databaseName: hireme
    user: hireme

services:
  - type: web
    name: hireme
    plan: free
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: hireme
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
